# Generated by Django 6.0.5 on 2026-05-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('personnel', '0002_permission_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='signe_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_signees', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='verrouille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_securise',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_med', to='personnel.personnel'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Validée', 'Validée')], default='En attente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', '-date'], name='patients_co_patient_1102b7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['statut'], name='patients_co_statut_5f8fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom', 'prenom'], name='patients_pa_nom_d8dfda_idx'),
        ),
    ]
