# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_permission_alter_personnel_options_and_more'),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Taille en octets', null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('duration_seconds', models.PositiveIntegerField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exécution de Backup',
                'verbose_name_plural': 'Exécutions de Backup',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backup_type', models.CharField(choices=[('database', 'Base de données'), ('media', 'Fichiers médias'), ('full', 'Backup complet')], max_length=20)),
                ('schedule', models.CharField(help_text='Cron expression', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('destination', models.CharField(help_text='S3 bucket ou chemin local', max_length=255)),
                ('encrypted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job de Backup',
                'verbose_name_plural': 'Jobs de Backup',
            },
        ),
        migrations.CreateModel(
            name='RestoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('test_database', models.CharField(help_text='Nom de la DB de test', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration_seconds', models.PositiveIntegerField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.backupexecution')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel')),
            ],
            options={
                'verbose_name': 'Test de Restauration',
                'verbose_name_plural': 'Tests de Restauration',
            },
        ),
        migrations.DeleteModel(
            name='BackupLog',
        ),
        migrations.AddField(
            model_name='backupexecution',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='backup.backupjob'),
        ),
    ]
