# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('dernier_active', models.DateTimeField(auto_now=True)),
                ('nom_appareil', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-dernier_active'],
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationpush',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationpush',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_push', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'statut'], name='chat_conver_patient_342a58_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['medicecin', 'statut'], name='chat_conver_medicec_0fab22_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-date_envoi'], name='chat_messag_convers_b5060e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lu', 'destinataire'], name='chat_messag_lu_adb518_idx'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
