# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentementpatient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demandeaccesdonnees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='consentementpatient',
            index=models.Index(fields=['patient', 'type_consentement'], name='consentemen_patient_eb310e_idx'),
        ),
    ]
