# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rendezvous',
            new_name='rendez_vous_medecin_2d6df0_idx',
            old_name='rdv_medecin_idx',
        ),
        migrations.RenameIndex(
            model_name='rendezvous',
            new_name='rendez_vous_patient_9221fa_idx',
            old_name='rdv_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='rendezvous',
            new_name='rendez_vous_statut_fe48d4_idx',
            old_name='rdv_statut_idx',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
