# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urgences', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passageurgences',
            new_name='urgences_pa_statut_cdc3b0_idx',
            old_name='urgences_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='passageurgences',
            new_name='urgences_pa_triage_115aeb_idx',
            old_name='urgences_triage_idx',
        ),
    ]
