# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_ligneprescription_id_alter_prescription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesoin',
            options={'verbose_name': 'Type de soin', 'verbose_name_plural': 'Types de soins'},
        ),
        migrations.AddField(
            model_name='planificationsoins',
            name='prescription_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soins_associes', to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='constantevitale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='constantevitale',
            name='mesure_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_mesurees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constantevitale',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='interventioninfirmiere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interventioninfirmiere',
            name='infirmier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planificationsoins',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planificationsoins',
            name='infirmier_assigne',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_a_realiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planificationsoins',
            name='realise_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_realises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typesoin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='constantevitale',
            index=models.Index(fields=['hospitalisation', 'type_constante', '-date_mesure'], name='soins_const_hospita_c66593_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationsoins',
            index=models.Index(fields=['hospitalisation', 'statut'], name='soins_plani_hospita_565afa_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationsoins',
            index=models.Index(fields=['date_heure_prevue', 'statut'], name='soins_plani_date_he_cdc240_idx'),
        ),
    ]
