# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_consultation_date_signature_consultation_signe_par_and_more'),
        ('personnel', '0002_permission_alter_personnel_options_and_more'),
        ('hospitalisations', '0002_rename_numero_lit_numero_lit_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'KPI Cache',
                'verbose_name_plural': 'KPI Caches',
            },
        ),
        migrations.CreateModel(
            name='NotificationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_notification', models.CharField(choices=[('alerte_stock', 'Alerte Stock Pharmacie'), ('alerte_patient', 'Alerte Patient'), ('alerte_resultat', 'Alerte Résultat Laboratoire'), ('gardiemodification', 'Modification de Garde'), ('systeme', 'Notification Système'), ('facturation', 'Alerte Facturation')], max_length=50)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation', '-priorite'],
            },
        ),
        migrations.CreateModel(
            name='SessionActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], max_length=20)),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('database', 'Base de Données'), ('cache', 'Cache Redis'), ('storage', 'Stockage Fichiers'), ('email', 'Service Email'), ('api_response', 'Temps de Réponse API'), ('disk_space', 'Espace Disque'), ('memory', 'Mémoire Système')], max_length=50)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Alerte'), ('ERROR', 'Erreur')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.DeleteModel(
            name='DashboardConfig',
        ),
        migrations.AddIndex(
            model_name='systemhealthlog',
            index=models.Index(fields=['check_type', '-checked_at'], name='dashboard_s_check_t_7b3a28_idx'),
        ),
        migrations.AddField(
            model_name='sessionactif',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_actives', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='notificationsysteme',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hospitalisations.hospitalisation'),
        ),
        migrations.AddField(
            model_name='notificationsysteme',
            name='lu_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_lues', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='notificationsysteme',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='patients.patient'),
        ),
    ]
