# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astreinte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='congesabsence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='congesabsence',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disponibilitemedecin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planninggarde',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planninggarde',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typegarde',
            name='coefficient_paiement',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='typegarde',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='planninggarde',
            index=models.Index(fields=['personnel', '-date_debut'], name='gardes_plan_personn_aaa5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='planninggarde',
            index=models.Index(fields=['statut'], name='gardes_plan_statut_b30b16_idx'),
        ),
        migrations.AddConstraint(
            model_name='planninggarde',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__gt', models.F('date_debut'))), name='date_fin_apres_debut'),
        ),
    ]
