# Generated by Django 6.0.5 on 2026-05-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(choices=[('patients', 'Patients'), ('hospitalisations', 'Hospitalisations'), ('laboratoire', 'Laboratoire'), ('pharmacie', 'Pharmacie'), ('facturation', 'Facturation'), ('personnel', 'Personnel'), ('audit', 'Audit'), ('dashboard', 'Dashboard')], max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['user__last_name']},
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='mfa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personnel',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], max_length=20)),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
