# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc_operatoire', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interventionchirurgicale',
            index=models.Index(fields=['statut', 'date_programmee'], name='bloc_operat_statut_31bf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionchirurgicale',
            index=models.Index(fields=['patient', '-date_programmee'], name='bloc_operat_patient_d082f9_idx'),
        ),
    ]
