# Generated by Django 6.0 on 2026-05-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('unite', models.CharField(default='comprimé', max_length=20)),
                ('seuil_alerte', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='LotMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_peremption', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie'), ('Ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.personnel')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie.lotmedicament')),
            ],
        ),
    ]
