# Generated by Django 6.0 on 2026-05-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=100)),
                ('priorite', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('statut', models.CharField(choices=[('Commande', 'Commande'), ('Prélèvement', 'Prélèvement'), ('Affectation', 'Affectation'), ('Saisie résultats', 'Saisie résultats'), ('Validé', 'Validé'), ('Publié', 'Publié')], default='Commande', max_length=20)),
                ('resultat', models.TextField(blank=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('resultat_immutable', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='patients.patient')),
                ('prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens_prescrits', to='personnel.personnel')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examens_traites', to='personnel.personnel')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examens_valides', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-date_prescription'],
            },
        ),
    ]
