# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examenimagerie',
            index=models.Index(fields=['patient', '-date_prescription'], name='imagerie_ex_patient_3c6932_idx'),
        ),
        migrations.AddIndex(
            model_name='examenimagerie',
            index=models.Index(fields=['statut', 'urgence'], name='imagerie_ex_statut_c34c53_idx'),
        ),
    ]
