# Generated by Django 6.0 on 2026-05-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('occupe', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisations.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_reelle', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Sorti', 'Sorti'), ('Transféré', 'Transféré')], default='Actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.personnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='patients.patient')),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalisations.lit')),
            ],
            options={
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitalisations.batiment')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hospitalisations.service'),
        ),
    ]
