# Generated by Django 6.0.5 on 2026-05-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisations', '0001_initial'),
        ('patients', '0002_consultation_date_signature_consultation_signe_par_and_more'),
        ('personnel', '0002_permission_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lit',
            old_name='numero',
            new_name='numero_lit',
        ),
        migrations.AlterUniqueTogether(
            name='lit',
            unique_together={('chambre', 'numero_lit')},
        ),
        migrations.AddField(
            model_name='batiment',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batiment',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batiment',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batiment',
            name='nombre_etages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chambre',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='tarif_nuitee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chambre',
            name='type_chambre',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Suite', 'Suite')], default='Simple', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lit',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lit',
            name='equipements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lit',
            name='statut',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupe', 'Occupé'), ('Indisponible', 'Indisponible')], default='Libre', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='chef_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='lit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='hospitalisations.lit'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='medecin_referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations_ref', to='personnel.personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('service', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('batiment', 'code')},
        ),
        migrations.AddIndex(
            model_name='hospitalisation',
            index=models.Index(fields=['patient', 'statut'], name='hospitalisa_patient_bacb95_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalisation',
            index=models.Index(fields=['statut'], name='hospitalisa_statut_cfa038_idx'),
        ),
        migrations.RemoveField(
            model_name='lit',
            name='occupe',
        ),
    ]
