# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nouveau_ne',
            options={'ordering': ['accouchement__date_heure']},
        ),
    ]
