# Generated by Django 4.2.30 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionteleconsultation',
            index=models.Index(fields=['statut', 'date_heure_prevue'], name='teleconsult_statut_58ce50_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionteleconsultation',
            index=models.Index(fields=['medecin', 'date_heure_prevue'], name='teleconsult_medecin_38aec0_idx'),
        ),
    ]
